[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
pin = true
trusted_config_paths = ["{{ env.XDG_PROJECTS_DIR }}"]
go_set_gobin = false
go_set_goroot = true

[tools]
node = "24"
uv = "latest"
